// Generated by Supabase MCP from project dfbyywvogeaxrxsriahp on 2026-04-30.
// Regenerate via: npx supabase gen types typescript --project-id dfbyywvogeaxrxsriahp > src/lib/supabase/database.types.ts
// Or: mcp__supabase__generate_typescript_types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      cities: {
        Row: {
          airport_time_min: number | null
          avg_property_price_jpy: number | null
          bus_to_slope_min: number | null
          car_to_slope_min: number | null
          closest_airport: string | null
          closest_station: string | null
          content_priority: Database["public"]["Enums"]["content_priority"] | null
          created_at: string
          description: string | null
          hero_image_path: string | null
          id: string
          latitude: number | null
          launch_priority: Database["public"]["Enums"]["launch_priority"]
          longitude: number | null
          municipality_url: string | null
          name_en: string
          name_ja: string
          notes: string | null
          off_season_activities_score: number | null
          population: number | null
          prefecture_id: string
          region_type: Database["public"]["Enums"]["region_type"] | null
          shuttle_bus: boolean | null
          slug: string
          sort_order: number
          station_time_min: number | null
          status: Database["public"]["Enums"]["taxonomy_status"]
          time_from_adelaide: string | null
          time_from_brisbane: string | null
          time_from_melbourne: string | null
          time_from_perth: string | null
          time_from_sydney: string | null
          updated_at: string
        }
        Insert: {
          airport_time_min?: number | null
          avg_property_price_jpy?: number | null
          bus_to_slope_min?: number | null
          car_to_slope_min?: number | null
          closest_airport?: string | null
          closest_station?: string | null
          content_priority?: Database["public"]["Enums"]["content_priority"] | null
          created_at?: string
          description?: string | null
          hero_image_path?: string | null
          id?: string
          latitude?: number | null
          launch_priority?: Database["public"]["Enums"]["launch_priority"]
          longitude?: number | null
          municipality_url?: string | null
          name_en: string
          name_ja: string
          notes?: string | null
          off_season_activities_score?: number | null
          population?: number | null
          prefecture_id: string
          region_type?: Database["public"]["Enums"]["region_type"] | null
          shuttle_bus?: boolean | null
          slug: string
          sort_order?: number
          station_time_min?: number | null
          status?: Database["public"]["Enums"]["taxonomy_status"]
          time_from_adelaide?: string | null
          time_from_brisbane?: string | null
          time_from_melbourne?: string | null
          time_from_perth?: string | null
          time_from_sydney?: string | null
          updated_at?: string
        }
        Update: {
          airport_time_min?: number | null
          avg_property_price_jpy?: number | null
          bus_to_slope_min?: number | null
          car_to_slope_min?: number | null
          closest_airport?: string | null
          closest_station?: string | null
          content_priority?: Database["public"]["Enums"]["content_priority"] | null
          created_at?: string
          description?: string | null
          hero_image_path?: string | null
          id?: string
          latitude?: number | null
          launch_priority?: Database["public"]["Enums"]["launch_priority"]
          longitude?: number | null
          municipality_url?: string | null
          name_en?: string
          name_ja?: string
          notes?: string | null
          off_season_activities_score?: number | null
          population?: number | null
          prefecture_id?: string
          region_type?: Database["public"]["Enums"]["region_type"] | null
          shuttle_bus?: boolean | null
          slug?: string
          sort_order?: number
          station_time_min?: number | null
          status?: Database["public"]["Enums"]["taxonomy_status"]
          time_from_adelaide?: string | null
          time_from_brisbane?: string | null
          time_from_melbourne?: string | null
          time_from_perth?: string | null
          time_from_sydney?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cities_prefecture_id_fkey"
            columns: ["prefecture_id"]
            isOneToOne: false
            referencedRelation: "prefectures"
            referencedColumns: ["id"]
          },
        ]
      }
      consent_records: {
        Row: {
          captured_at: string
          consent_text_body: string
          consent_text_hash: string
          consent_text_version: string
          id: string
          ip_hash: string | null
          scope: string
          user_agent: string | null
          user_id: string
          withdrawal_reason: string | null
          withdrawn_at: string | null
        }
        Insert: {
          captured_at?: string
          consent_text_body: string
          consent_text_hash: string
          consent_text_version: string
          id?: string
          ip_hash?: string | null
          scope: string
          user_agent?: string | null
          user_id: string
          withdrawal_reason?: string | null
          withdrawn_at?: string | null
        }
        Update: {
          captured_at?: string
          consent_text_body?: string
          consent_text_hash?: string
          consent_text_version?: string
          id?: string
          ip_hash?: string | null
          scope?: string
          user_agent?: string | null
          user_id?: string
          withdrawal_reason?: string | null
          withdrawn_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "consent_records_consent_text_version_fkey"
            columns: ["consent_text_version"]
            isOneToOne: false
            referencedRelation: "consent_text_versions"
            referencedColumns: ["version"]
          },
        ]
      }
      consent_text_versions: {
        Row: {
          body: string
          body_hash: string
          created_at: string
          effective_from: string
          effective_until: string | null
          id: string
          scope: string
          version: string
        }
        Insert: {
          body: string
          body_hash: string
          created_at?: string
          effective_from?: string
          effective_until?: string | null
          id?: string
          scope: string
          version: string
        }
        Update: {
          body?: string
          body_hash?: string
          created_at?: string
          effective_from?: string
          effective_until?: string | null
          id?: string
          scope?: string
          version?: string
        }
        Relationships: []
      }
      design_styles: {
        Row: {
          created_at: string
          description: string | null
          description_long: string | null
          id: string
          key_features: string | null
          name_en: string
          name_ja: string
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["taxonomy_status"]
          typical_regions: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          description_long?: string | null
          id?: string
          key_features?: string | null
          name_en: string
          name_ja: string
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          typical_regions?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          description_long?: string | null
          id?: string
          key_features?: string | null
          name_en?: string
          name_ja?: string
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          typical_regions?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      events: {
        Row: {
          created_at: string
          event_type: Database["public"]["Enums"]["event_type"]
          id: string
          payload: Json | null
          session_id: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          event_type: Database["public"]["Enums"]["event_type"]
          id?: string
          payload?: Json | null
          session_id: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          event_type?: Database["public"]["Enums"]["event_type"]
          id?: string
          payload?: Json | null
          session_id?: string
          user_id?: string | null
        }
        Relationships: []
      }
      follow_up_surveys: {
        Row: {
          completed_at: string | null
          context: Json | null
          created_at: string
          id: string
          lead_id: string | null
          recipient_email: string
          recipient_name: string | null
          responses: Json | null
          sent_at: string
          token: string
        }
        Insert: {
          completed_at?: string | null
          context?: Json | null
          created_at?: string
          id?: string
          lead_id?: string | null
          recipient_email: string
          recipient_name?: string | null
          responses?: Json | null
          sent_at?: string
          token: string
        }
        Update: {
          completed_at?: string | null
          context?: Json | null
          created_at?: string
          id?: string
          lead_id?: string | null
          recipient_email?: string
          recipient_name?: string | null
          responses?: Json | null
          sent_at?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "follow_up_surveys_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      form_submissions: {
        Row: {
          consent: boolean
          created_at: string
          email: string
          id: string
          lead_status: string | null
          message: string
          name: string
          source: string | null
          source_context: Json | null
          user_id: string | null
        }
        Insert: {
          consent?: boolean
          created_at?: string
          email: string
          id?: string
          lead_status?: string | null
          message: string
          name: string
          source?: string | null
          source_context?: Json | null
          user_id?: string | null
        }
        Update: {
          consent?: boolean
          created_at?: string
          email?: string
          id?: string
          lead_status?: string | null
          message?: string
          name?: string
          source?: string | null
          source_context?: Json | null
          user_id?: string | null
        }
        Relationships: []
      }
      journey_bookmarks: {
        Row: {
          created_at: string
          id: string
          linked_property_slugs: string[]
          og_description: string | null
          og_favicon_url: string | null
          og_fetched_at: string | null
          og_image_url: string | null
          og_site_name: string | null
          og_title: string | null
          phase: string | null
          updated_at: string
          url: string
          url_canonical: string
          url_hash: string
          user_id: string
          user_note: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          linked_property_slugs?: string[]
          og_description?: string | null
          og_favicon_url?: string | null
          og_fetched_at?: string | null
          og_image_url?: string | null
          og_site_name?: string | null
          og_title?: string | null
          phase?: string | null
          updated_at?: string
          url: string
          url_canonical: string
          url_hash: string
          user_id: string
          user_note?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          linked_property_slugs?: string[]
          og_description?: string | null
          og_favicon_url?: string | null
          og_fetched_at?: string | null
          og_image_url?: string | null
          og_site_name?: string | null
          og_title?: string | null
          phase?: string | null
          updated_at?: string
          url?: string
          url_canonical?: string
          url_hash?: string
          user_id?: string
          user_note?: string | null
        }
        Relationships: []
      }
      journey_notes: {
        Row: {
          body: string
          created_at: string
          id: string
          linked_property_slugs: string[]
          phase: string
          pinned: boolean
          updated_at: string
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          linked_property_slugs?: string[]
          phase: string
          pinned?: boolean
          updated_at?: string
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          linked_property_slugs?: string[]
          phase?: string
          pinned?: boolean
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      journey_signals: {
        Row: {
          captured_at: string
          id: string
          metadata: Json
          phase_after: string
          phase_before: string
          signal_type: string
          user_id: string
        }
        Insert: {
          captured_at?: string
          id?: string
          metadata?: Json
          phase_after: string
          phase_before: string
          signal_type: string
          user_id: string
        }
        Update: {
          captured_at?: string
          id?: string
          metadata?: Json
          phase_after?: string
          phase_before?: string
          signal_type?: string
          user_id?: string
        }
        Relationships: []
      }
      land_building_details: {
        Row: {
          category: string
          created_at: string
          description: string | null
          id: string
          name_en: string
          name_ja: string | null
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["taxonomy_status"]
          updated_at: string
        }
        Insert: {
          category: string
          created_at?: string
          description?: string | null
          id?: string
          name_en: string
          name_ja?: string | null
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          updated_at?: string
        }
        Update: {
          category?: string
          created_at?: string
          description?: string | null
          id?: string
          name_en?: string
          name_ja?: string | null
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          updated_at?: string
        }
        Relationships: []
      }
      leads: {
        Row: {
          area_slug: string
          consent_record_id: string
          created_at: string
          id: string
          katitas_reference: string | null
          listing_id: string | null
          notes: string | null
          prefecture_slug: string
          profile_snapshot: Json
          status: string
          status_updated_at: string
          user_id: string
          withdrawn_at: string | null
        }
        Insert: {
          area_slug: string
          consent_record_id: string
          created_at?: string
          id?: string
          katitas_reference?: string | null
          listing_id?: string | null
          notes?: string | null
          prefecture_slug: string
          profile_snapshot: Json
          status?: string
          status_updated_at?: string
          user_id: string
          withdrawn_at?: string | null
        }
        Update: {
          area_slug?: string
          consent_record_id?: string
          created_at?: string
          id?: string
          katitas_reference?: string | null
          listing_id?: string | null
          notes?: string | null
          prefecture_slug?: string
          profile_snapshot?: Json
          status?: string
          status_updated_at?: string
          user_id?: string
          withdrawn_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "leads_consent_record_id_fkey"
            columns: ["consent_record_id"]
            isOneToOne: false
            referencedRelation: "consent_records"
            referencedColumns: ["id"]
          },
        ]
      }
      local_areas: {
        Row: {
          city_id: string
          created_at: string
          id: string
          name_en: string
          name_ja: string | null
          notes: string | null
          region_type: Database["public"]["Enums"]["region_type"] | null
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["taxonomy_status"]
          updated_at: string
        }
        Insert: {
          city_id: string
          created_at?: string
          id?: string
          name_en: string
          name_ja?: string | null
          notes?: string | null
          region_type?: Database["public"]["Enums"]["region_type"] | null
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          updated_at?: string
        }
        Update: {
          city_id?: string
          created_at?: string
          id?: string
          name_en?: string
          name_ja?: string | null
          notes?: string | null
          region_type?: Database["public"]["Enums"]["region_type"] | null
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "local_areas_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "cities"
            referencedColumns: ["id"]
          },
        ]
      }
      og_cache: {
        Row: {
          error_count: number
          expires_at: string
          fetch_error: string | null
          fetched_at: string
          og_description: string | null
          og_favicon_url: string | null
          og_image_url: string | null
          og_site_name: string | null
          og_title: string | null
          url_canonical: string
          url_hash: string
        }
        Insert: {
          error_count?: number
          expires_at?: string
          fetch_error?: string | null
          fetched_at?: string
          og_description?: string | null
          og_favicon_url?: string | null
          og_image_url?: string | null
          og_site_name?: string | null
          og_title?: string | null
          url_canonical: string
          url_hash: string
        }
        Update: {
          error_count?: number
          expires_at?: string
          fetch_error?: string | null
          fetched_at?: string
          og_description?: string | null
          og_favicon_url?: string | null
          og_image_url?: string | null
          og_site_name?: string | null
          og_title?: string | null
          url_canonical?: string
          url_hash?: string
        }
        Relationships: []
      }
      policy_acknowledgments: {
        Row: {
          acknowledged_at: string
          context: string
          doc_type: string
          id: string
          ip_address: string | null
          user_agent: string | null
          user_id: string | null
          version: string
        }
        Insert: {
          acknowledged_at?: string
          context: string
          doc_type: string
          id?: string
          ip_address?: string | null
          user_agent?: string | null
          user_id?: string | null
          version: string
        }
        Update: {
          acknowledged_at?: string
          context?: string
          doc_type?: string
          id?: string
          ip_address?: string | null
          user_agent?: string | null
          user_id?: string | null
          version?: string
        }
        Relationships: []
      }
      prefectures: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name_en: string
          name_ja: string
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["taxonomy_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name_en: string
          name_ja: string
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name_en?: string
          name_ja?: string
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          updated_at?: string
        }
        Relationships: []
      }
      price_ranges: {
        Row: {
          created_at: string
          description: string | null
          id: string
          max_aud: number | null
          max_jpy: number | null
          min_aud: number | null
          min_jpy: number | null
          name_en: string
          name_ja: string
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["taxonomy_status"]
          target_segment: string | null
          typical_property_types: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          max_aud?: number | null
          max_jpy?: number | null
          min_aud?: number | null
          min_jpy?: number | null
          name_en: string
          name_ja: string
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          target_segment?: string | null
          typical_property_types?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          max_aud?: number | null
          max_jpy?: number | null
          min_aud?: number | null
          min_jpy?: number | null
          name_en?: string
          name_ja?: string
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          target_segment?: string | null
          typical_property_types?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      property_conditions: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name_en: string
          name_ja: string | null
          notes: string | null
          quiz_weight: Database["public"]["Enums"]["use_case_priority"]
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["taxonomy_status"]
          target_persona: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name_en: string
          name_ja?: string | null
          notes?: string | null
          quiz_weight?: Database["public"]["Enums"]["use_case_priority"]
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          target_persona?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name_en?: string
          name_ja?: string | null
          notes?: string | null
          quiz_weight?: Database["public"]["Enums"]["use_case_priority"]
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          target_persona?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      property_types: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name_en: string
          name_ja: string
          price_range_text: string | null
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["taxonomy_status"]
          typical_regions: string | null
          typical_use: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name_en: string
          name_ja: string
          price_range_text?: string | null
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          typical_regions?: string | null
          typical_use?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name_en?: string
          name_ja?: string
          price_range_text?: string | null
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          typical_regions?: string | null
          typical_use?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      rate_limit: {
        Row: {
          bucket_key: string
          tokens: number
          window_start: string
        }
        Insert: {
          bucket_key: string
          tokens?: number
          window_start?: string
        }
        Update: {
          bucket_key?: string
          tokens?: number
          window_start?: string
        }
        Relationships: []
      }
      quiz_responses: {
        Row: {
          created_at: string
          id: string
          quiz_type: string
          responses: Json
          session_id: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          quiz_type: string
          responses?: Json
          session_id: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          quiz_type?: string
          responses?: Json
          session_id?: string
          user_id?: string | null
        }
        Relationships: []
      }
      renovation_features: {
        Row: {
          buyer_relevance: string | null
          category: Database["public"]["Enums"]["renovation_category"]
          created_at: string
          description: string | null
          id: string
          japan_specific: boolean
          name_en: string
          name_ja: string
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["taxonomy_status"]
          updated_at: string
        }
        Insert: {
          buyer_relevance?: string | null
          category: Database["public"]["Enums"]["renovation_category"]
          created_at?: string
          description?: string | null
          id?: string
          japan_specific?: boolean
          name_en: string
          name_ja: string
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          updated_at?: string
        }
        Update: {
          buyer_relevance?: string | null
          category?: Database["public"]["Enums"]["renovation_category"]
          created_at?: string
          description?: string | null
          id?: string
          japan_specific?: boolean
          name_en?: string
          name_ja?: string
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          updated_at?: string
        }
        Relationships: []
      }
      saves: {
        Row: {
          content_id: string
          content_type: string
          created_at: string
          href: string | null
          id: string
          title: string | null
          user_id: string | null
        }
        Insert: {
          content_id: string
          content_type: string
          created_at?: string
          href?: string | null
          id?: string
          title?: string | null
          user_id?: string | null
        }
        Update: {
          content_id?: string
          content_type?: string
          created_at?: string
          href?: string | null
          id?: string
          title?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      use_cases: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name_en: string
          name_ja: string
          priority: Database["public"]["Enums"]["use_case_priority"]
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["taxonomy_status"]
          target_buyers: string | null
          typical_property_types: string | null
          typical_regions: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name_en: string
          name_ja: string
          priority?: Database["public"]["Enums"]["use_case_priority"]
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          target_buyers?: string | null
          typical_property_types?: string | null
          typical_regions?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name_en?: string
          name_ja?: string
          priority?: Database["public"]["Enums"]["use_case_priority"]
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["taxonomy_status"]
          target_buyers?: string | null
          typical_property_types?: string | null
          typical_regions?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      user_journey_state: {
        Row: {
          buyer_type: string | null
          created_at: string
          phase: string
          phase_overridden_at: string | null
          phase_set_via: string
          updated_at: string
          user_id: string
        }
        Insert: {
          buyer_type?: string | null
          created_at?: string
          phase?: string
          phase_overridden_at?: string | null
          phase_set_via?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          buyer_type?: string | null
          created_at?: string
          phase?: string
          phase_overridden_at?: string | null
          phase_set_via?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      content_priority: "high" | "medium" | "low"
      event_type:
        | "page_view"
        | "quiz_start"
        | "quiz_complete"
        | "area_view"
        | "property_type_view"
        | "save"
        | "unsave"
        | "contact_form"
        | "cta_click"
        | "comparison_view"
        | "article_read"
        | "bookmark_add"
        | "bookmark_remove"
        | "compare_add"
        | "compare_remove"
        | "filter_apply"
      launch_priority: "P1" | "P2" | "P3" | "P4" | "out_of_scope"
      region_type:
        | "ski_resort"
        | "rural_town"
        | "coastal"
        | "onsen_town"
        | "urban_access"
        | "mountain_village"
        | "lakeside"
      renovation_category:
        | "wet_areas"
        | "interior"
        | "exterior"
        | "maintenance_safety"
        | "comfort_performance"
        | "unique_to_japan"
      taxonomy_status: "active" | "inactive" | "later"
      use_case_priority: "high" | "medium" | "low"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
