#!/usr/bin/env python3
"""Parse CRA-76 XLSX and generate taxonomy seed SQL."""

import re
import openpyxl

XLSX_PATH = '/Users/craefto/Desktop/Japanoma/docs/JapaTak-Taxonomy-CRA76-signed off.xlsx'
OUTPUT_PATH = '/Users/craefto/Desktop/Japanoma/.worktrees/sprint-1/supabase/migrations/004_seed_taxonomy.sql'

def slugify(text):
    s = text.lower().strip()
    s = re.sub(r'[^a-z0-9\s-]', '', s)
    s = re.sub(r'[\s]+', '-', s)
    s = re.sub(r'-+', '-', s)
    return s.strip('-')

def escape_sql(val):
    if val is None:
        return 'NULL'
    s = str(val).strip()
    return "'" + s.replace("'", "''") + "'"

def map_priority(raw):
    if raw is None:
        return 'out_of_scope'
    r = str(raw).strip()
    if r.startswith('P1'):
        return 'P1'
    if r.startswith('P2'):
        return 'P2'
    if r.startswith('P3'):
        return 'P3'
    if r.startswith('P4'):
        return 'P4'
    return 'out_of_scope'

def map_status(raw_priority):
    p = map_priority(raw_priority)
    if p == 'P1':
        return 'active'
    if p == 'out_of_scope':
        return 'inactive'
    return 'later'

def map_region_type(raw):
    if raw is None:
        return None
    mapping = {
        'ski resort': 'ski_resort',
        'ski resort suburb': 'ski_resort',
        'rural town': 'rural_town',
        'coastal': 'coastal',
        'onsen town': 'onsen_town',
        'hot spring + ski': 'onsen_town',
        'urban access': 'urban_access',
        'urban/investment': 'urban_access',
        'urban/commercial': 'urban_access',
        'cultural/urban': 'urban_access',
        'cultural/heritage': 'rural_town',
        'mountain village': 'mountain_village',
        'lakeside': 'lakeside',
        'beach/resort': 'coastal',
    }
    key = str(raw).strip().lower()
    return mapping.get(key)

def map_renovation_category(raw):
    if raw is None:
        return 'interior'
    mapping = {
        'wet areas': 'wet_areas',
        'interior': 'interior',
        'exterior': 'exterior',
        'maintenance & safety': 'maintenance_safety',
        'maintenance_safety': 'maintenance_safety',
        'comfort & performance': 'comfort_performance',
        'comfort_performance': 'comfort_performance',
        'unique to japan': 'unique_to_japan',
        'unique_to_japan': 'unique_to_japan',
    }
    key = str(raw).strip().lower()
    return mapping.get(key, 'interior')

def parse_currency(val):
    if val is None:
        return None
    s = str(val).strip().replace('¥', '').replace('A$', '').replace(',', '').replace('+', '')
    try:
        return int(float(s))
    except (ValueError, TypeError):
        return None

def map_use_case_priority(raw):
    if raw is None:
        return 'medium'
    r = str(raw).strip().lower()
    if 'high' in r:
        return 'high'
    if 'low' in r:
        return 'low'
    return 'medium'

wb = openpyxl.load_workbook(XLSX_PATH, data_only=True)
lines = ['-- Taxonomy seed data from CRA-76 signed-off XLSX', '-- Auto-generated by scripts/generate-seed-sql.py', '']

# === PREFECTURES ===
ws = wb['Geographic Hierarchy']
prefectures = {}
pref_order = 0
for row in ws.iter_rows(min_row=4, values_only=True):
    if row[0] is None:
        continue
    pref_en = str(row[0]).strip()
    if pref_en not in prefectures:
        pref_ja = str(row[1]).strip() if row[1] else ''
        pref_order += 1
        prefectures[pref_en] = {'ja': pref_ja, 'slug': slugify(pref_en), 'order': pref_order}

lines.append('-- Prefectures')
for name_en, info in sorted(prefectures.items(), key=lambda x: x[1]['order']):
    lines.append(
        f"INSERT INTO prefectures (slug, name_en, name_ja, status, sort_order) "
        f"VALUES ({escape_sql(info['slug'])}, {escape_sql(name_en)}, {escape_sql(info['ja'])}, 'active', {info['order']});"
    )
lines.append('')

# === CITIES ===
seen_cities = set()
city_order = 0
lines.append('-- Cities')
for row in ws.iter_rows(min_row=4, values_only=True):
    if row[0] is None or row[2] is None:
        continue
    pref_en = str(row[0]).strip()
    city_en = str(row[2]).strip()
    key = (pref_en, city_en)
    if key in seen_cities:
        continue
    seen_cities.add(key)
    city_order += 1

    city_ja = str(row[3]).strip() if row[3] else ''
    region_type = map_region_type(row[6])
    priority = map_priority(row[7])
    status = map_status(row[7])
    notes = str(row[9]).strip() if row[9] else ''
    airport = str(row[11]).strip() if row[11] else None
    airport_min = int(row[12]) if row[12] else None
    station = str(row[13]).strip() if row[13] else None
    station_min = int(row[14]) if row[14] else None
    pref_slug = prefectures[pref_en]['slug']
    city_slug = slugify(city_en)

    rt_sql = f"'{region_type}'" if region_type else 'NULL'
    airport_sql = escape_sql(airport) if airport else 'NULL'
    airport_min_sql = str(airport_min) if airport_min else 'NULL'
    station_sql = escape_sql(station) if station else 'NULL'
    station_min_sql = str(station_min) if station_min else 'NULL'

    lines.append(
        f"INSERT INTO cities (slug, name_en, name_ja, description, status, sort_order, "
        f"prefecture_id, launch_priority, region_type, closest_airport, airport_time_min, "
        f"closest_station, station_time_min, notes) "
        f"VALUES ({escape_sql(city_slug)}, {escape_sql(city_en)}, {escape_sql(city_ja)}, '', "
        f"'{status}', {city_order}, "
        f"(SELECT id FROM prefectures WHERE slug = {escape_sql(pref_slug)}), "
        f"'{priority}', {rt_sql}, {airport_sql}, {airport_min_sql}, "
        f"{station_sql}, {station_min_sql}, {escape_sql(notes)});"
    )
lines.append('')

# === PROPERTY TYPES ===
ws = wb['Property Types']
lines.append('-- Property Types')
pt_order = 0
for row in ws.iter_rows(min_row=2, values_only=True):
    if row[0] is None or not str(row[0]).startswith('PT'):
        continue
    pt_order += 1
    name_en = str(row[1]).strip()
    name_ja = str(row[2]).strip() if row[2] else ''
    desc = str(row[3]).strip() if row[3] else ''
    typical_use = str(row[4]).strip() if row[4] else ''
    typical_regions = str(row[5]).strip() if row[5] else ''
    price_range = str(row[6]).strip() if row[6] else ''
    scope = str(row[8]).strip() if row[8] else ''
    status = 'active' if 'In Scope' in scope else 'inactive'

    lines.append(
        f"INSERT INTO property_types (slug, name_en, name_ja, description, status, sort_order, "
        f"typical_use, typical_regions, price_range_text) "
        f"VALUES ({escape_sql(slugify(name_en))}, {escape_sql(name_en)}, {escape_sql(name_ja)}, "
        f"{escape_sql(desc)}, '{status}', {pt_order}, "
        f"{escape_sql(typical_use)}, {escape_sql(typical_regions)}, {escape_sql(price_range)});"
    )
lines.append('')

# === USE CASES ===
ws = wb['Use Cases']
lines.append('-- Use Cases')
uc_order = 0
for row in ws.iter_rows(min_row=2, values_only=True):
    if row[0] is None or not str(row[0]).startswith('UC'):
        continue
    uc_order += 1
    name_en = str(row[1]).strip()
    name_ja = str(row[2]).strip() if row[2] else ''
    desc = str(row[3]).strip() if row[3] else ''
    target = str(row[4]).strip() if row[4] else ''
    prop_types = str(row[5]).strip() if row[5] else ''
    regions = str(row[6]).strip() if row[6] else ''
    priority = map_use_case_priority(row[7])

    lines.append(
        f"INSERT INTO use_cases (slug, name_en, name_ja, description, status, sort_order, "
        f"target_buyers, typical_property_types, typical_regions, priority) "
        f"VALUES ({escape_sql(slugify(name_en))}, {escape_sql(name_en)}, {escape_sql(name_ja)}, "
        f"{escape_sql(desc)}, 'active', {uc_order}, "
        f"{escape_sql(target)}, {escape_sql(prop_types)}, {escape_sql(regions)}, '{priority}');"
    )
lines.append('')

# === DESIGN STYLES ===
ws = wb['Design Styles']
lines.append('-- Design Styles')
ds_order = 0
for row in ws.iter_rows(min_row=2, values_only=True):
    if row[0] is None or not str(row[0]).startswith('DS'):
        continue
    ds_order += 1
    name_en = str(row[1]).strip()
    name_ja = str(row[2]).strip() if row[2] else ''
    desc = str(row[3]).strip() if row[3] else ''
    key_features = str(row[4]).strip() if row[4] else ''

    lines.append(
        f"INSERT INTO design_styles (slug, name_en, name_ja, description, status, sort_order, "
        f"description_long, key_features, typical_regions) "
        f"VALUES ({escape_sql(slugify(name_en))}, {escape_sql(name_en)}, {escape_sql(name_ja)}, "
        f"{escape_sql(desc)}, 'active', {ds_order}, "
        f"{escape_sql(desc)}, {escape_sql(key_features)}, '');"
    )
lines.append('')

# === PRICE RANGES ===
ws = wb['Price Ranges']
lines.append('-- Price Ranges')
pr_order = 0
for row in ws.iter_rows(min_row=3, values_only=True):
    if row[0] is None or not str(row[0]).startswith('PR'):
        continue
    pr_order += 1
    name_en = str(row[1]).strip()
    name_ja = str(row[2]).strip() if row[2] else ''
    min_jpy = parse_currency(row[3])
    max_jpy = parse_currency(row[4])
    min_aud = parse_currency(row[5])
    max_aud = parse_currency(row[6])
    target = str(row[7]).strip() if row[7] else ''
    prop_types = str(row[8]).strip() if row[8] else ''

    lines.append(
        f"INSERT INTO price_ranges (slug, name_en, name_ja, description, status, sort_order, "
        f"min_jpy, max_jpy, min_aud, max_aud, target_segment, typical_property_types) "
        f"VALUES ({escape_sql(slugify(name_en))}, {escape_sql(name_en)}, {escape_sql(name_ja)}, "
        f"'', 'active', {pr_order}, "
        f"{min_jpy if min_jpy else 'NULL'}, {max_jpy if max_jpy else 'NULL'}, "
        f"{min_aud if min_aud else 'NULL'}, {max_aud if max_aud else 'NULL'}, "
        f"{escape_sql(target)}, {escape_sql(prop_types)});"
    )
lines.append('')

# === RENOVATION FEATURES ===
ws = wb['Renovation Features']
lines.append('-- Renovation Features')
rf_order = 0
for row in ws.iter_rows(min_row=2, values_only=True):
    if row[0] is None or not str(row[0]).startswith('RF'):
        continue
    rf_order += 1
    name_en = str(row[1]).strip()
    name_ja = str(row[2]).strip() if row[2] else ''
    category = map_renovation_category(row[3])
    desc = str(row[4]).strip() if row[4] else ''
    japan_specific = str(row[6]).strip().lower() in ('yes', 'true', '1') if row[6] else False

    lines.append(
        f"INSERT INTO renovation_features (slug, name_en, name_ja, description, status, sort_order, "
        f"category, japan_specific) "
        f"VALUES ({escape_sql(slugify(name_en))}, {escape_sql(name_en)}, {escape_sql(name_ja)}, "
        f"{escape_sql(desc)}, 'active', {rf_order}, "
        f"'{category}', {'true' if japan_specific else 'false'});"
    )

with open(OUTPUT_PATH, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f'Generated {OUTPUT_PATH}')
print(f'  Prefectures: {len(prefectures)}')
print(f'  Cities: {len(seen_cities)}')
print(f'  Property Types: {pt_order}')
print(f'  Use Cases: {uc_order}')
print(f'  Design Styles: {ds_order}')
print(f'  Price Ranges: {pr_order}')
print(f'  Renovation Features: {rf_order}')
