-- Migration: 013_taxonomy_cra76_refresh_data
-- Data seed for CRA-76 taxonomy refresh (Kaz, Mar 2026).
-- See docs/taxonomy/cra76-gap-analysis-2026-04-23.md.

BEGIN;

-- 1. Fix slug typo: 'yamanochi' -> 'yamanouchi' (matches xlsx spelling)
UPDATE cities SET slug = 'yamanouchi' WHERE slug = 'yamanochi';

-- 2. New cities (not in previous seed)
INSERT INTO cities (slug, name_en, name_ja, description, status, sort_order, prefecture_id, launch_priority, region_type, closest_airport, airport_time_min, closest_station, station_time_min, shuttle_bus, bus_to_slope_min, car_to_slope_min, notes, time_from_sydney, time_from_melbourne, time_from_brisbane, time_from_perth, time_from_adelaide, avg_property_price_jpy, off_season_activities_score)
VALUES ('yuzawa', 'Yuzawa', '湯沢町', '', 'active', 0, (SELECT id FROM prefectures WHERE slug = 'niigata'), 'P1', 'ski_resort', 'Niigata (KIJ)', 86, 'Echigo-Yuzawa (越後湯沢)', 20, true, NULL, 15, 'Joetsu Kokusai, Gala Yuzawa, Yuzawa Kogen, Naspa Ski Garden, Yuzawa Nakazato, Kandatsu, Kagura, Naeba', '11:41', '12:21', '11:26', '11:56', '14:31', 11570000, 8)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO cities (slug, name_en, name_ja, description, status, sort_order, prefecture_id, launch_priority, region_type, closest_airport, airport_time_min, closest_station, station_time_min, shuttle_bus, bus_to_slope_min, car_to_slope_min, notes, time_from_sydney, time_from_melbourne, time_from_brisbane, time_from_perth, time_from_adelaide, avg_property_price_jpy, off_season_activities_score)
VALUES ('higashikawa', 'Higashikawa', '東川町', '', 'active', 0, (SELECT id FROM prefectures WHERE slug = 'hokkaido'), 'P1', 'ski_resort', 'Asahikawa Airport (AKJ)', 49, 'Asahikawa (旭川)', 10, true, NULL, 30, 'Kamui Ski Links', '12:05', '12:45', '12:55', '13:25', '14:55', 12760000, 5)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO cities (slug, name_en, name_ja, description, status, sort_order, prefecture_id, launch_priority, region_type, closest_airport, airport_time_min, closest_station, station_time_min, shuttle_bus, bus_to_slope_min, car_to_slope_min, notes, time_from_sydney, time_from_melbourne, time_from_brisbane, time_from_perth, time_from_adelaide, avg_property_price_jpy, off_season_activities_score)
VALUES ('sapporo', 'Sapporo', '札幌市', '', 'active', 0, (SELECT id FROM prefectures WHERE slug = 'hokkaido'), 'P1', 'ski_resort', 'New Chitose Airport (CTS)', 28, 'Sapporo (札幌)', 10, true, NULL, NULL, 'Sapporo Kokusai Ski Resort, Sapporo Teine', '11:23', '12:33', '11:33', '12:03', '14:53', 38040000, 7)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO cities (slug, name_en, name_ja, description, status, sort_order, prefecture_id, launch_priority, region_type, closest_airport, airport_time_min, closest_station, station_time_min, shuttle_bus, bus_to_slope_min, car_to_slope_min, notes, time_from_sydney, time_from_melbourne, time_from_brisbane, time_from_perth, time_from_adelaide, avg_property_price_jpy, off_season_activities_score)
VALUES ('yubari', 'Yubari', '夕張市', '', 'active', 0, (SELECT id FROM prefectures WHERE slug = 'hokkaido'), 'P1', 'ski_resort', 'New Chitose Airport (CTS)', 50, 'Shin-Yubari (新夕張)', 20, false, 0, NULL, 'Mount Recey Ski Area', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (slug) DO NOTHING;

-- 3. Priority updates (17 cities promoted to P1/P2 Launch per Kaz)
UPDATE cities SET launch_priority = 'P2' WHERE slug = 'furano' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'hokkaido');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'asahikawa' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'hokkaido');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'otaru' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'hokkaido');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'minakami' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'gunma');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'numata' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'gunma');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'nasushiobara' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'tochigi');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'inawashiro' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'fukushima');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'shiroishi' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'miyagi');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'yamagata' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'yamagata');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'nishikawa' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'yamagata');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'tsuruoka' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'yamagata');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'kitakami' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'iwate');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'hanamaki' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'iwate');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'hachimantai' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'iwate');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'semboku' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'akita');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'kita-akita' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'akita');
UPDATE cities SET launch_priority = 'P1' WHERE slug = 'aomori' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'aomori');

-- 4. Populate AU enrichment columns (29 P1 cities with data)
UPDATE cities SET time_from_sydney = '12:23', time_from_melbourne = '13:03', time_from_brisbane = '12:08', time_from_perth = '12:38', time_from_adelaide = '15:13', avg_property_price_jpy = 6040000, off_season_activities_score = 8 WHERE slug = 'iiyama' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'nagano');
UPDATE cities SET time_from_sydney = '12:23', time_from_melbourne = '13:03', time_from_brisbane = '12:08', time_from_perth = '12:38', time_from_adelaide = '15:13', avg_property_price_jpy = 5200000, off_season_activities_score = 7 WHERE slug = 'kijimadaira' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'nagano');
UPDATE cities SET time_from_sydney = '12:40', time_from_melbourne = '13:20', time_from_brisbane = '12:25', time_from_perth = '12:55', time_from_adelaide = '15:30', avg_property_price_jpy = 4150000, off_season_activities_score = 7 WHERE slug = 'nakano' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'nagano');
UPDATE cities SET time_from_sydney = '12:40', time_from_melbourne = '13:20', time_from_brisbane = '12:25', time_from_perth = '12:55', time_from_adelaide = '15:30', avg_property_price_jpy = 4150000, off_season_activities_score = 7 WHERE slug = 'yamanouchi' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'nagano');
UPDATE cities SET time_from_sydney = '12:40', time_from_melbourne = '13:20', time_from_brisbane = '12:25', time_from_perth = '12:55', time_from_adelaide = '15:30', avg_property_price_jpy = 6200000, off_season_activities_score = 8 WHERE slug = 'shinano' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'nagano');
UPDATE cities SET time_from_sydney = '12:40', time_from_melbourne = '13:20', time_from_brisbane = '12:25', time_from_perth = '12:55', time_from_adelaide = '15:30', avg_property_price_jpy = 5600000, off_season_activities_score = 7 WHERE slug = 'iizuna' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'nagano');
UPDATE cities SET time_from_sydney = '12:40', time_from_melbourne = '13:20', time_from_brisbane = '12:25', time_from_perth = '12:55', time_from_adelaide = '15:30', avg_property_price_jpy = 4150000, off_season_activities_score = 7 WHERE slug = 'shimotakai' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'nagano');
UPDATE cities SET time_from_sydney = '12:50', time_from_melbourne = '13:30', time_from_brisbane = '12:35', time_from_perth = '13:05', time_from_adelaide = '15:40', avg_property_price_jpy = 9020000, off_season_activities_score = 7 WHERE slug = 'myoko' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'niigata');
UPDATE cities SET time_from_sydney = '12:26', time_from_melbourne = '13:06', time_from_brisbane = '12:11', time_from_perth = '12:41', time_from_adelaide = '15:16', avg_property_price_jpy = 4300000, off_season_activities_score = 6 WHERE slug = 'shibata' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'niigata');
UPDATE cities SET time_from_sydney = '12:28', time_from_melbourne = '13:08', time_from_brisbane = '12:13', time_from_perth = '12:43', time_from_adelaide = '15:18', avg_property_price_jpy = 3800000, off_season_activities_score = 6 WHERE slug = 'agano' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'niigata');
UPDATE cities SET time_from_sydney = '12:32', time_from_melbourne = '13:12', time_from_brisbane = '12:17', time_from_perth = '12:47', time_from_adelaide = '15:22', avg_property_price_jpy = 3600000, off_season_activities_score = 6 WHERE slug = 'gosen' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'niigata');
UPDATE cities SET time_from_sydney = '11:56', time_from_melbourne = '12:36', time_from_brisbane = '11:41', time_from_perth = '12:11', time_from_adelaide = '14:46', avg_property_price_jpy = 7800000, off_season_activities_score = 7 WHERE slug = 'uonuma' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'niigata');
UPDATE cities SET time_from_sydney = '11:41', time_from_melbourne = '12:21', time_from_brisbane = '11:26', time_from_perth = '11:56', time_from_adelaide = '14:31', avg_property_price_jpy = 11570000, off_season_activities_score = 8 WHERE slug = 'yuzawa' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'niigata');
UPDATE cities SET time_from_sydney = '12:10', time_from_melbourne = '12:50', time_from_brisbane = '11:55', time_from_perth = '12:25', time_from_adelaide = '15:00', avg_property_price_jpy = 5430000, off_season_activities_score = 7 WHERE slug = 'minakami' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'gunma');
UPDATE cities SET time_from_sydney = '12:20', time_from_melbourne = '13:00', time_from_brisbane = '12:05', time_from_perth = '12:35', time_from_adelaide = '15:10', avg_property_price_jpy = 11960000, off_season_activities_score = 6 WHERE slug = 'numata' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'gunma');
UPDATE cities SET time_from_sydney = '11:41', time_from_melbourne = '12:21', time_from_brisbane = '11:26', time_from_perth = '11:56', time_from_adelaide = '14:31', avg_property_price_jpy = 14840000, off_season_activities_score = 6 WHERE slug = 'nasushiobara' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'tochigi');
UPDATE cities SET time_from_sydney = '12:30', time_from_melbourne = '13:10', time_from_brisbane = '12:15', time_from_perth = '12:45', time_from_adelaide = '15:20', avg_property_price_jpy = 17650000, off_season_activities_score = 7 WHERE slug = 'inawashiro' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'fukushima');
UPDATE cities SET time_from_sydney = '12:32', time_from_melbourne = '13:12', time_from_brisbane = '12:17', time_from_perth = '12:47', time_from_adelaide = '15:22', avg_property_price_jpy = 4940000, off_season_activities_score = 6 WHERE slug = 'shiroishi' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'miyagi');
UPDATE cities SET time_from_sydney = '12:57', time_from_melbourne = '13:37', time_from_brisbane = '12:42', time_from_perth = '13:12', time_from_adelaide = '15:47', avg_property_price_jpy = 28580000, off_season_activities_score = 9 WHERE slug = 'yamagata' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'yamagata');
UPDATE cities SET time_from_sydney = '13:32', time_from_melbourne = '14:12', time_from_brisbane = '13:17', time_from_perth = '13:47', time_from_adelaide = '16:22', avg_property_price_jpy = 4800000, off_season_activities_score = 8 WHERE slug = 'nishikawa' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'yamagata');
UPDATE cities SET time_from_sydney = '12:48', time_from_melbourne = '13:28', time_from_brisbane = '12:33', time_from_perth = '13:03', time_from_adelaide = '15:38', avg_property_price_jpy = 7600000, off_season_activities_score = 9 WHERE slug = 'tsuruoka' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'yamagata');
UPDATE cities SET time_from_sydney = '11:23', time_from_melbourne = '12:03', time_from_brisbane = '11:38', time_from_perth = '12:08', time_from_adelaide = '14:53', avg_property_price_jpy = 4300000, off_season_activities_score = 6 WHERE slug = 'hanamaki' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'iwate');
UPDATE cities SET time_from_sydney = '12:08', time_from_melbourne = '12:48', time_from_brisbane = '11:53', time_from_perth = '12:23', time_from_adelaide = '15:08', avg_property_price_jpy = 5200000, off_season_activities_score = 7 WHERE slug = 'hachimantai' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'iwate');
UPDATE cities SET time_from_sydney = '12:02', time_from_melbourne = '12:42', time_from_brisbane = '12:52', time_from_perth = '13:22', time_from_adelaide = '14:52', avg_property_price_jpy = 2700000, off_season_activities_score = 6 WHERE slug = 'kita-akita' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'akita');
UPDATE cities SET time_from_sydney = '11:43', time_from_melbourne = '12:23', time_from_brisbane = '12:33', time_from_perth = '13:03', time_from_adelaide = '14:33', avg_property_price_jpy = 14440000, off_season_activities_score = 7 WHERE slug = 'aomori' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'aomori');
UPDATE cities SET time_from_sydney = '12:15', time_from_melbourne = '12:55', time_from_brisbane = '13:05', time_from_perth = '13:35', time_from_adelaide = '15:05', avg_property_price_jpy = 12760000, off_season_activities_score = 6 WHERE slug = 'asahikawa' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'hokkaido');
UPDATE cities SET time_from_sydney = '12:05', time_from_melbourne = '12:45', time_from_brisbane = '12:55', time_from_perth = '13:25', time_from_adelaide = '14:55', avg_property_price_jpy = 12760000, off_season_activities_score = 5 WHERE slug = 'higashikawa' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'hokkaido');
UPDATE cities SET time_from_sydney = '12:05', time_from_melbourne = '13:15', time_from_brisbane = '12:15', time_from_perth = '12:45', time_from_adelaide = '15:35', avg_property_price_jpy = 6900000, off_season_activities_score = 7 WHERE slug = 'otaru' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'hokkaido');
UPDATE cities SET time_from_sydney = '11:23', time_from_melbourne = '12:33', time_from_brisbane = '11:33', time_from_perth = '12:03', time_from_adelaide = '14:53', avg_property_price_jpy = 38040000, off_season_activities_score = 7 WHERE slug = 'sapporo' AND prefecture_id = (SELECT id FROM prefectures WHERE slug = 'hokkaido');

-- 5. Land & Building Details — 41 rows from Kazs taxonomy
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-01', 'Structure Type', 'Wooden / Wood-framed', '木造', 'Standard for single-family detached houses.', 1) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-02', 'Structure Type', 'Steel-framed', '鉄骨造', '"Light-gauge steel" is common for pre-fab houses.', 2) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-03', 'Structure Type', 'Reinforced Concrete (RC)', '鉄筋コンクリート造', 'Standard for mid-to-high-rise apartments.', 3) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-04', 'Structure Type', 'Steel Reinforced Concrete (SRC)', '鉄骨鉄筋コンクリート造', 'Used for skyscrapers or high-rise buildings.', 4) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-05', 'Structure Type', 'Reinforced Concrete Block (CB)', '補強コンクリートブロック造', 'Common for garden walls or older small structures.', 5) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-06', 'Stories & Styles', 'Single-story / One-story', '平屋（1階建て）', 'A simple house with no stairs.', 6) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-07', 'Stories & Styles', 'Bungalow', '平屋（小規模）', 'A cozy, single-story house with a front porch.', 7) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-08', 'Stories & Styles', '2-story / Two-story', '2階建て', 'A two-level home, most common in urban areas.', 8) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-09', 'Stories & Styles', '3-story / Three-story', '3階建て', 'A multi-level home, common in urban areas.', 9) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-10', 'Stories & Styles', 'With a basement', '地下1階付き', 'Indicates the house includes a lower level below ground.', 10) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-11', 'Stories & Styles', 'High-rise', '高層（マンション等）', 'Typically a building with 10+ floors.', 11) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-12', 'Stories & Styles', 'Mid-rise', '中層', 'Buildings ranging from 5 to 9 floors.', 12) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-13', 'Stories & Styles', 'Low-rise', '低層', 'Buildings with fewer than 4 floors.', 13) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-14', 'Stories & Styles', 'With a loft / With an attic', 'ロフト付き', 'Extra space built under the roof for storage or living.', 14) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-15', 'Land Rights', 'Freehold', '所有権', 'Full ownership of both land and building.', 15) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-16', 'Land Rights', 'Leasehold', '借地権', 'Right to use the land for a set period (renting land).', 16) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-17', 'Land Category', 'Residential Land (Takuchi)', '宅地', 'Land approved for building a house.', 17) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-18', 'Land Category', 'Farmland / Forest', '農地 / 山林', 'Land not currently zoned for residential building.', 18) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-19', 'Land-use zoning', 'Category 1 Low-Rise Exclusive', '第1種低層住居専用地域', 'Strictly for low-rise houses (quiet areas).', 19) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-20', 'Land-use zoning', 'Commercial Zone', '商業地域', 'Areas for shops, offices, and large buildings.', 20) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-21', 'Land-use zoning', 'Industrial Zone', '工業地域', 'Areas primarily for factories and plants.', 21) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-22', 'Urban Planning', 'Urbanization Area', '市街化区域', 'Areas prioritized for development and infrastructure.', 22) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-23', 'Urban Planning', 'Urbanization Control Area', '市街化調整区域', 'Development is restricted to preserve nature/farmland.', 23) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-24', 'Building Ratio', 'Coverage / Floor Area Ratio', '建ぺい率 / 容積率', 'Coverage: footprint vs land. Floor Area: total space vs land.', 24) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-25', 'Year Built', 'Year Built / Construction Date', '築年月', 'Shows the age of the building (e.g., Oct 1975). Pre-1981 buildings were built under the old code, hence more likely to have insufficient seismic resistance, and critical to check if there has been retrofit (耐震補強) reinforcement.', 25) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-26', 'Renovation History', 'Interior or/and Exterior renovation log', 'リフォーム履歴', 'List of major reforms completed (Year)', 26) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-27', 'Road Access', 'Corner lot (width in m)', '角地', 'Located at an intersection; better light/ventilation.', 27) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-28', 'Road Access', 'Single-side access (width in m)', '一方路', 'The property faces only one street.', 28) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-29', 'Road Access', 'Public Road / Private Road (width in m)', '公道 / 私道', 'Public (government-owned) vs Private (privately-owned).', 29) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-30', 'Setback', 'Setback: Not required', 'セットバック不要', 'No need to move the building back for road widening.', 30) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-31', 'Setback', 'Setback: Required', 'セットバック要', 'Must leave space between the road and building line.', 31) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-32', 'Current status', 'Vacant', '現状', 'Already vacated', 32) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-33', 'Current status', 'Occupied', '現状', 'Previous owner is still living / In use', 33) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-34', 'Current status', 'Abandonned', '現状', 'Previous owner''s belongings are still there', 34) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-35', 'Handover Date', 'Immediate', '引渡し日', 'Move-in ready', 35) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-36', 'Handover Date', 'Future Date', '引渡し日', 'Not yet move-in ready', 36) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-37', 'Warranty', 'Yes', '保証', 'Structural/Defect warranty included (Seller’s independent warranty)', 37) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-38', 'Warranty', 'No', '保証', 'As is, and no additional warranty', 38) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-39', 'Minpaku-zoning', 'Short Term Rental permitted', '住宅宿泊事業許可地域', 'a) Not ina standard city use zone, b) Outside the city planning area, c) no school or kindergarten w/in 110m proximity are pre-requisites (No single site that can verify all).  Then apply then await to see if application was accepted for a final confirmation pending Fire-law compliance and other legal checks are clear.', 39) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-40', 'Sewage', 'Septic Tank', '浄化槽', 'While not connected city/town underground sewer system, it has septic tank.', 40) ON CONFLICT (slug) DO NOTHING;
INSERT INTO land_building_details (slug, category, name_en, name_ja, description, sort_order) VALUES ('lb-41', 'Sewage', 'Holding Tank', '汲取槽', 'While not connected city/town underground sewer system, it has holding tank.', 41) ON CONFLICT (slug) DO NOTHING;

COMMIT;
